trigger:
  branches:
    include:
      - main

pr:
  branches:
    exclude:
      - '*'

resources:
  repositories:
    - repository: eShopOnWeb
      type: github
      endpoint: arghabumba
      name: dotnet-architecture/eShopOnWeb

variables:
  dockerRegistryServiceConnection: 'ACRSC'
  dockerfilePath: '$(Build.SourcesDirectory)/src/Web/Dockerfile'
  repository: '$(imageRepository)'
  prefix: '$(tagPrefix)'
  tag: '$(prefix)-$(Build.BuildId)'

jobs:
  - job: Debug
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - script: ls -l /home/vsts/work/1/s/test/UnitTests/
        displayName: 'List contents of UnitTests directory'

  - job: BuildAndTest
    dependsOn: Debug
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - script: dotnet test /home/vsts/work/1/s/test/UnitTests/UnitTests.csproj --configuration Release --no-build
        displayName: 'Run unit tests'

      - task: Docker@2
        inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          repository: $(repository)
          command: 'buildAndPush'
          Dockerfile: $(dockerfilePath)
          tags: |
            $(tag)
          buildContext: $(Build.SourcesDirectory)/src/Web
