trigger:
  branches:
    include:
      - main

pr:
  branches:
    exclude:
      - '*'

resources:
  repositories:
    - repository: eShopOnWeb
      type: github
      endpoint: arghabumba
      name: dotnet-architecture/eShopOnWeb

variables:
  dockerRegistryServiceConnection: 'ACRSC'
  dockerfilePath: '$(Build.SourcesDirectory)/src/Web/Dockerfile'
  repository: '$(imageRepository)'
  prefix: '$(tagPrefix)'
  tag: '$(prefix)-$(Build.BuildId)'

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: eShopOnWeb
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet build $(Build.SourcesDirectory)/src/Web/Web.csproj --configuration Release
    displayName: 'Build the .NET Core app'

  - script: dotnet test $(Build.SourcesDirectory)/test/UnitTests/UnitTests.csproj --configuration Release --no-build
    displayName: 'Run unit tests'

  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: $(repository)
      command: 'buildAndPush'
      Dockerfile: $(dockerfilePath)
      tags: |
          $(tag)
      buildContext: $(Build.SourcesDirectory)/src/Web
