trigger:
  branches:
    include:
      - main

pr:
  branches:
    exclude:
      - '*'

resources:
  repositories:
    - repository: eShopOnWeb
      type: github
      endpoint: arghabumba
      name: dotnet-architecture/eShopOnWeb

variables:
  dockerRegistryServiceConnection: 'ACRSC'
  dockerfilePath: '$(Build.SourcesDirectory)/src/Web/Dockerfile'
  repository: '$(imageRepository)'
  prefix: '$(tagPrefix)'
  tag: '$(prefix)-$(Build.BuildId)'

jobs:
  - job: Debug
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - script: ls -l tests/UnitTests/
        displayName: 'List contents of UnitTests directory'

  - job: BuildAndTest
    dependsOn: Debug
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - script: dotnet clean $(Build.SourcesDirectory)/path-to-your-project.csproj
        displayName: 'Clean the project'

      - script: dotnet restore $(Build.SourcesDirectory)/path-to-your-project.csproj
        displayName: 'Restore the project'

      - script: dotnet build $(Build.SourcesDirectory)/path-to-your-project.csproj --configuration Release
        displayName: 'Build the project'

      - script: dotnet test tests/UnitTests/UnitTests.csproj --configuration Release --no-build
        displayName: 'Run unit tests'

      - task: Docker@2
        inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          repository: $(repository)
          command: 'buildAndPush'
          Dockerfile: $(dockerfilePath)
          tags: |
            $(tag)
          buildContext: $(Build.SourcesDirectory)/src/Web
